### ISSUE TITLE
README for Sprint 1

### ISSUE THREAD

**Issue by gurtejboparai** [louismacvux/bookwyrm#7]
Make the readme ready for sprint 1 evaluation.

**Comment by CameronJung** [comment]
I'll go flesh out the project description.

**Comment by CameronJung** [comment]
Added a link to a more detailed project description in the wiki home to the readme. I think somebody else should probably handle the languages and tools section since I don't have the best understanding of the APIs we're using.

**Comment by louismacvux** [comment]
I've updated the Languages and Tools. I just put in what we have discussed so far. We haven't decided on what API we will be using yet and we still haven't discussed MongoDB after the meeting with TA so I left those fields TBD.
